steps:
  # - name: "gcr.io/cloud-builders/docker"
  #   args: ["build", "-t", "gcr.io/${PROJECT_ID}/cloudrun-example:${SHORT_SHA}", "-t", "gcr.io/${PROJECT_ID}/cloudrun-example:latest", "."]

  # - name: "gcr.io/cloud-builders/docker"
  #   args: ["push", "gcr.io/${PROJECT_ID}/cloudrun-example:${SHORT_SHA}"]

  # - name: "gcr.io/cloud-builders/docker"
  #   entrypoint: /bin/bash
  #   args:
  #   - "-c"
  #   - |
  #     set -ex
  #     docker build -t "gcr.io/${PROJECT_ID}/cloudrun-example:${SHORT_SHA}" -t "gcr.io/${PROJECT_ID}/cloudrun-example:latest" .
  #     docker push "gcr.io/${PROJECT_ID}/cloudrun-example"

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        set -ex
        docker build -t "${_DEFAULT_REGION}-docker.pkg.dev/${PROJECT_ID}/container-repository/${REPO_NAME}:dev-${SHORT_SHA}" .
        docker push "${_DEFAULT_REGION}-docker.pkg.dev/${PROJECT_ID}/container-repository/${REPO_NAME}:dev-${SHORT_SHA}"
        # docker build -t "gcr.io/${PROJECT_ID}/${REPO_NAME}:dev-${SHORT_SHA}" .
        # docker push "gcr.io/${PROJECT_ID}/${REPO_NAME}:dev-${SHORT_SHA}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        set -ex
        gcloud run deploy ${REPO_NAME}-${BRANCH_NAME} \
          --image ${_DEFAULT_REGION}-docker.pkg.dev/${PROJECT_ID}/container-repository/${REPO_NAME}:dev-${SHORT_SHA} \
          --region ${_DEFAULT_REGION} \
          --platform managed \
          --allow-unauthenticated
          #--vpc-connector ${_CONNECTOR_NAME} \

# us-central1-docker.pkg.dev/prj-sre-d-sandbox-run-c366/container-repository
# docker pull \
#    us-central1-docker.pkg.dev/prj-sre-d-sandbox-run-c366/container-repository/cloudrun-example:dev-14eaa66
# images:
#   - "gcr.io/${PROJECT_ID}/cloudrun-example:${SHORT_SHA}"
#   - "gcr.io/${PROJECT_ID}/cloudrun-example:latest"

# https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
substitutions:
  _POLICY_REPO: '' # add path to policies here https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#how-to-use-terraform-validator

# Cloud Build Timeout
timeout: 3600s
