timeout: 7200s

# https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
substitutions:
  _POLICY_REPO: '' # add path to policies here https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#how-to-use-terraform-validator

steps:
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args: ["auth", "list"]

  # - name: "gcr.io/cloud-builders/docker"
  #   args: ["build", "-t", "gcr.io/${PROJECT_ID}/cloudrun-example", "."]

  # - name: "gcr.io/cloud-builders/docker"
  #   args: ["push", "gcr.io/${PROJECT_ID}/cloudrun-example"]

  # Uses 195303305359@cloudbuild.gserviceaccount.com
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args: ["beta", "run", "deploy", "my-springboot-service", "--image", "gcr.io/${PROJECT_ID}/cloudrun-example:latest", "--platform", "managed", "--region", "${_DEFAULT_REGION}"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        set -ex
        gcloud run deploy ${REPO_NAME}-${_ENVIRONMENT} \
          --image ${_DEFAULT_REGION}-docker.pkg.dev/${PROJECT_ID}/container-repository/${REPO_NAME}:dev-${SHORT_SHA} \
          --region ${_DEFAULT_REGION} \
          --platform managed \
          --allow-unauthenticated
          #--vpc-connector ${_CONNECTOR_NAME} \
          # --image ${_DEFAULT_REGION}-docker.pkg.dev/${PROJECT_ID}/container-repository/${REPO_NAME}:dev-${SHORT_SHA} \

# images:
#   - "gcr.io/$PROJECT_ID/deploy/cloudrun-example"
