timeout: 7200s
# https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
substitutions:
  _POLICY_REPO: '' # add path to policies here https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#how-to-use-terraform-validator
steps:
  # - name: "gcr.io/cloud-builders/docker"
  #   args: ["build", "-t", "gcr.io/${PROJECT_ID}/cloudrun-example:${SHORT_SHA}", "-t", "gcr.io/${PROJECT_ID}/cloudrun-example:latest", "."]

  # - name: "gcr.io/cloud-builders/docker"
  #   args: ["push", "gcr.io/${PROJECT_ID}/cloudrun-example:${SHORT_SHA}"]

  # - name: "gcr.io/cloud-builders/docker"
  #   entrypoint: /bin/bash
  #   args:
  #   - "-c"
  #   - |
  #     set -ex
  #     docker build -t "gcr.io/${PROJECT_ID}/cloudrun-example:${SHORT_SHA}" -t "gcr.io/${PROJECT_ID}/cloudrun-example:latest" .
  #     docker push "gcr.io/${PROJECT_ID}/cloudrun-example"

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        set -ex
        docker build -t "gcr.io/${PROJECT_ID}/${REPO_NAME}:dev-${SHORT_SHA}" .
        docker push "gcr.io/${PROJECT_ID}/${REPO_NAME}:dev-${SHORT_SHA}"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        set -ex
        gcloud run deploy ${BRANCH_NAME}-${REPO_NAME} \
          --image gcr.io/${PROJECT_ID}/${REPO_NAME}:dev-${SHORT_SHA} \
          --region ${_DEFAULT_REGION}
          --platform managed
          #--vpc-connector ${_CONNECTOR_NAME} \

# images:
#   - "gcr.io/${PROJECT_ID}/cloudrun-example:${SHORT_SHA}"
#   - "gcr.io/${PROJECT_ID}/cloudrun-example:latest"
